### ISSUE TITLE
arduino uno r4 wifi support

### ISSUE THREAD

**Issue by LYB030** [blynkkk/BlynkNcpExample#3]
`pio run -e rp2040connect -t upload_ncp
UnknownEnvNamesError: Unknown environment names 'rp2040connect'. Valid names are 'uno_r4_wifi'`

Is the error due to uno r4 wifi not being fully supported yet?

**Comment by vshymanskyy** [comment]
You need to re-flash ESP module on your board.

## 1. Manually put  the UNO R4 WiFi in ESP mode

1. Disconnect the UNO R4 WiFi from your PC
2. Short the pins highlighted in the image using a jumper wire

![image](https://github.com/pennam/UnoR4WiFiUpdate/assets/20436476/b271759e-5d7b-44f5-954e-15bc0f7feae9)

3. Connect the UNO R4 WiFi to your PC

## 2. Upload the Blynk.NCP firmware

```sh
pio run -e unoR4wifi -t upload_ncp
```

## 3. Upload the main MCU (Renesas) firmware

Edit `src/main.cpp` to include your Temlate info, then run:

```sh
pio run -e unoR4wifi -t upload -t monitor
```

**Comment by LYB030** [comment]
![image](https://github.com/blynkkk/BlynkNcpExample/assets/42745293/44b66dea-234c-4ec5-9f9d-8a1043e215c6)
i just got this error,thanks for help!

**Comment by vshymanskyy** [comment]
This repository ( https://github.com/blynkkk/BlynkNcpExample ) IS the example. Use it, not just any arbitrary PlatformIO project.

**Comment by LYB030** [comment]
![image](https://github.com/blynkkk/BlynkNcpExample/assets/42745293/ca35859d-d610-487c-b0b3-7cb359209dfb)
i just clone the project,but i got error on this
 `C:\Users\94837\.platformio\python3\python.exe: can't open file 'E:\BlynkNcpExample\esptool.py': [Errno 2] No such file or directory
*** Error 2
*** [upload_ncp] Explicit exit, status 1`

**Comment by LYB030** [comment]
looks like the esptool.py is missing in BlynkNcpexample

**Comment by vshymanskyy** [comment]
@ivankravets take a glance please

**Comment by vshymanskyy** [comment]
@LYB030 please install it manually:
```sh
pio pkg install --global --tool "platformio/tool-esptoolpy"
```
and retry `upload_ncp`

**Comment by LYB030** [comment]
![image](https://github.com/blynkkk/BlynkNcpExample/assets/42745293/f52c2809-069a-4df5-8aba-a2d70694ad5b)
The esptool is already installed, and it looks like the script keeps looking for esptool.py in the BlynkNcpExample path

**Comment by vshymanskyy** [comment]
I'll report this problem to PlatformIO.
you should be able to run:
```
%HOMEDRIVE%%HOMEPATH%\.platformio\python3\python.exe %HOMEDRIVE%%HOMEPATH%\.platformio\packages\tool-esptoolpy\esptool.py
```
if not, inspect your `C:\Users\94837\.platformio\` folder

**Comment by LYB030** [comment]
![image](https://github.com/blynkkk/BlynkNcpExample/assets/42745293/ae27d43c-4676-41d2-a38f-490827fbc837)
hope the Scripts can be fixed as soon as possible,I get the above error when I manually run python scripts

**Comment by vshymanskyy** [comment]
This is all related to platformio, will take a look tomorrow or as Ivan from PIO can find time.

Meanwhile, you can flash https://github.com/blynkkk/BlynkNcpDriver/releases/latest/download/BlynkNCP_uno_r4_wifi.flash.bin NCP firmware at address 0, using any available ESP32 flasher tool

**Comment by vshymanskyy** [comment]
It's also possible, that installing the full ESP32 package can solve your issue:
```sh
pio pkg install --global --platform "platformio/espressif32"
```

**Comment by LYB030** [comment]
> It's also possible, that installing the full ESP32 package can solve your issue:
> 
> ```shell
> pio pkg install --global --platform "platformio/espressif32"
> ```

still same problem, thanks your help!

**Comment by vshymanskyy** [comment]
@LYB030 looks like the issue was addressed on the Platformio side, please update your PIO to the latest development branch: `pio upgrade --dev` and retry

**Comment by LYB030** [comment]
<img width="517" alt="image" src="https://github.com/blynkkk/BlynkNcpExample/assets/42745293/818e3bf0-df0e-4aeb-9618-9205407117b0">
after i run `pio run -e unoR4wifi -t upload` i got above error

**Comment by vshymanskyy** [comment]
Are you sure the example is unmodified (except for setting the Template ID) ?
I just retested with the same version of libraries and it works:
```log
PLATFORM: Renesas RA (0.0.2) > Arduino Uno R4 WiFi
HARDWARE: RA4M1 48MHz, 32KB RAM, 256KB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, jlink)
PACKAGES: 
 - framework-arduinorenesas-uno @ 1.0.1 
 - tool-bossac @ 1.10901.0 (1.9.1) 
 - toolchain-gccarmnoneeabi @ 1.100301.220327 (10.3.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 18 compatible libraries
Scanning dependencies...
Dependency Graph
|-- Blynk @ 1.3.0+sha.5dd3047
|-- BlynkNcpDriver @ 0.6.1+sha.13fd027
|-- SoftwareSerial @ 1.0
Building in release mode
Checking size .pio/build/unoR4wifi/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  21.6% (used 7076 bytes from 32768 bytes)
Flash: [==        ]  19.2% (used 50208 bytes from 262144 bytes)
=============================== [SUCCESS] Took 0.72 seconds ===============================
```

The only visible difference is, I'm using `Renesas RA (0.0.2)`

Can you try: `pio pkg update -g -p renesas-ra`

**Comment by LYB030** [comment]
amazing after i use `pio pkg update -g -p renesas-ra` the uplaod success!

**Comment by LYB030** [comment]
@vshymanskyy 

> the device is online! but i try to scan the QR code which is no response on my smart phone, i use "find device nearby" to find device and set up the wifi connection!thanks for your kind help@vshymanskyy

@vshymanskyy thanks your kind help

**Comment by vshymanskyy** [comment]
Great! Happy coding 👾👾👾
