### ISSUE TITLE
Questions about WiFi provisioning with uno r4 wifi board

### ISSUE THREAD

**Issue by LYB030** [blynkkk/BlynkNcpExample#5]
![image](https://github.com/blynkkk/BlynkNcpExample/assets/42745293/aea1689b-1324-4149-805e-d84817a664d5)
According to the document, I can press and hold a button for 10 seconds to perform Re-provisioning new WiFi credentials. However, I'm not sure which button it is. Is it the reset button? My board is Uno R4 WiFi.

Currently, when I bring the board to a new WiFi environment, I can only reset the board by re-uploading the sketch. I urgently need a physical button to reset the WiFi settings. I couldn't find the "setting.h" file in the original directory.

**Comment by vshymanskyy** [comment]
`uno r4 wifi` doesn't have any buttons connected to the ESP32, so ESP32 cannot handle any button presses by itself.
So, you need to attach and handle the button in your code (I suggest using `mathertel/OneButton` library), and then call `Blynk.resetConfig()` when you need to erase the previous configuration.

**Comment by LYB030** [comment]
thanks help!

**Comment by vshymanskyy** [comment]
@LYB030 check out this: https://github.com/blynkkk/BlynkNcpExample/commit/4050855272118e559d974d404db688ec0475a75b
