### ISSUE TITLE
Unable to connect to Arduino Nano 33 IOT

### ISSUE THREAD

**Issue by Tal-Mo** [blynkkk/BlynkNcpExample#6]
Hello,

1. I am trying to connect my Arduino Nano 33 IOT to the console, but I am unable to do so. Please provide exact instruction + code. 
I have connected ESP32 without any problem.
2. I would like to connect by IOT devices to my mobile phone via BLE. Are you supporting this option?

**Comment by vshymanskyy** [comment]
1. Please follow the README instructions, this repository contains the full code example.
2. BLE is used for device provisioning/activation only. After that, the device connects to the cloud directlyover WiFi (or Ethernet, Cellular in some cases)

**Comment by Tal-Mo** [comment]
1. I am using Arduino IDE 2.1.1 and can not replace it.
2. I have installed BlynkMcpDriver and used the only example. I have replaced Template ID and name that I generated from the Console, but it is not working.
3. Do you have specific example for Arduino Nano 33 IOT using Arduino IDE?

**Comment by vshymanskyy** [comment]
There is no direct example for BlynkNcpDriver on  Arduino Nano 33 IOT, and probably it's not what you need.

Please install the latest Blynk library from Arduino Library Manager (v1.3.0), and you will be able to use the 
`Blynk -> Blynk.Edgent -> Edgent_NCP` example.

However, you will have to figure out a way to flash the NINA module on Arduino Nano 33 IOT with Blynk.NCP.
This is not trivial, and this PlatformIO example automates it for you.

**Comment by vshymanskyy** [comment]
Was this resolved?

**Comment by Tal-Mo** [comment]
No it was not.
I was surprised that the NCP is not working for Nano IOT. I thought that
this was its purpose.
However, working with ESP32 seems to be working fine.
My next generation PCB will be with ESP32 and I will give it another try
then

**Comment by vshymanskyy** [comment]
It is verified to work on Nano 33 Iot.

**Comment by Tal-Mo** [comment]
the example on the Arduino IDE does not work for me

**Comment by vshymanskyy** [comment]
Sorry, but "the example doesn't work" description is not enough to
understand.

**Comment by Tal-Mo** [comment]
"However, you will have to figure out a way to flash the NINA module on
Arduino Nano 33 IOT with Blynk.NCP.
This is not trivial, and this PlatformIO example automates it for you."

I am working with Arduino IDE, not PlatformIO, and the example in Arduino
does not provide connection.

**Comment by vshymanskyy** [comment]
So, this PlatformIO example allows you to run NCP on Nano 33 IoT in 2 simple steps:
- Flash NCP: `pio run -e nano33iot -t upload_ncp`
- Flash main MCU: `pio run -e nano33iot -t upload -t monitor`

There are currently no instructions on how to do that without PlataformIO.

**Comment by Tal-Mo** [comment]
I understand.
Since I am not going to change my IDE for this issue, I will check how we
can work in the future with ESP32.
