### ISSUE TITLE
Blynk.NCP nano33iot not connecting to blynk 

### ISSUE THREAD

**Issue by Sachinmc73** [blynkkk/BlynkNcpExample#7]
hi 
I am planning to use the new NCP feature on my nano33iot based devices. but when using the given example on platform io I'm getting the following error.
```
[3461] Main1 firmware: 0.1.0
[3461] Build: Aug  2 2023 15:25:21
[3462] 
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ v1.3.0 on Nano 33 IoT

 #StandWithUkraine    https://bit.ly/swua


[13731] Cannot communicate to Blynk.NCP
```

please help with this.

also, I am interested in knowing how actually the network co-processor is flashed with new firmware and where is the source code for network co-processor

**Comment by vshymanskyy** [comment]
Hi. Did you run `pio run -e nano33iot -t upload_ncp` ?

**Comment by vshymanskyy** [comment]
The NCP flashing is performed by this script:
https://github.com/blynkkk/BlynkNcpExample/blob/main/tools/extra_upload_ncp.py

The NCP source code is proprietary.

**Comment by vshymanskyy** [comment]
is this resolved?

**Comment by Sachinmc73** [comment]
> Hi. Did you run `pio run -e nano33iot -t upload_ncp` ?

yes

**Comment by Sachinmc73** [comment]
> is this resolved?
No still facing the same issue

**Comment by vshymanskyy** [comment]
please describe in details, what you do and what results you see

**Comment by Sachinmc73** [comment]
I think once my nano is up and running I am suppose to use may phone to find the device and connect to it. but couldn't find any devices under wifi and on nano's terminal it says  "[13731] Cannot communicate to Blynk.NCP"

**Comment by vshymanskyy** [comment]
The provided information is not enough to understand your problem.
Please describe what happens when you run `upload_ncp` command, provide logs and so on.

**Comment by Sachinmc73** [comment]
I have uploaded the log (terminal output)  that i get when I run upload_ncp command in the first question of this thread itself.
the build and upload operation is succesfull without any issues but I cannot able to connect the nano to blynk.

**Comment by Sachinmc73** [comment]
sorry I missed that.
now I have attached the log.

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
PS C:\Users\123sa\Desktop\BlynkNcpExample-main> pio run -e nano33iot -t upload_ncp
Processing nano33iot (platform: atmelsam; board: nano_33_iot; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelsam/nano_33_iot.html
PLATFORM: Atmel SAM (8.1.0) > NANO 33 IoT
HARDWARE: SAMD21G18A 48MHz, 32KB RAM, 256KB Flash
DEBUG: Current (atmel-ice) External (atmel-ice, blackmagic, jlink)
PACKAGES:
 - framework-arduino-samd @ 1.8.13
 - framework-cmsis @ 1.40500.0 (4.5.0)
 - framework-cmsis-atmel @ 1.2.2
 - tool-bossac @ 1.10700.190624 (1.7.0)
 - toolchain-gccarmnoneeabi @ 1.70201.0 (7.2.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 16 compatible libraries
Scanning dependencies...
Dependency Graph
|-- Blynk @ 1.3.0
|-- BlynkNcpDriver @ 0.6.2
|-- ArduinoOTA @ 1.0.10
|-- OneButton @ 2.1.0
Building in release mode
upload_ncp(["upload_ncp"], [])
Getting Blynk.NCP release info
Downloading BlynkNCP_nina_w102.flash.bin ...
pio run -d tools/BlynkNcpFlasher -e nano33iot --target upload
Processing nano33iot (platform: atmelsam; board: nano_33_iot; framework: arduino)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelsam/nano_33_iot.html
PLATFORM: Atmel SAM (8.1.0) > NANO 33 IoT
HARDWARE: SAMD21G18A 48MHz, 32KB RAM, 256KB Flash
DEBUG: Current (atmel-ice) External (atmel-ice, blackmagic, jlink)
PACKAGES:
 - framework-arduino-samd @ 1.8.13
 - framework-cmsis @ 1.40500.0 (4.5.0)
 - framework-cmsis-atmel @ 1.2.2
 - tool-bossac @ 1.10700.190624 (1.7.0)
 - toolchain-gccarmnoneeabi @ 1.70201.0 (7.2.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 12 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Compiling .pio\build\nano33iot\src\main.cpp.o
Compiling .pio\build\nano33iot\FrameworkArduinoVariant\variant.cpp.o
Compiling .pio\build\nano33iot\FrameworkArduino\Reset.cpp.o
Compiling .pio\build\nano33iot\FrameworkArduino\SERCOM.cpp.o
Compiling .pio\build\nano33iot\FrameworkArduino\Tone.cpp.o
Compiling .pio\build\nano33iot\FrameworkArduino\USB\CDC.cpp.o
Compiling .pio\build\nano33iot\FrameworkArduino\USB\USBCore.cpp.o
Compiling .pio\build\nano33iot\FrameworkArduino\USB\samd21_host.c.o
Compiling .pio\build\nano33iot\FrameworkArduino\Uart.cpp.o
Compiling .pio\build\nano33iot\FrameworkArduino\WInterrupts.c.o
Compiling .pio\build\nano33iot\FrameworkArduino\WMath.cpp.o
Compiling .pio\build\nano33iot\FrameworkArduino\abi.cpp.o
In file included from C:\Users\123sa\.platformio\packages\framework-arduino-samd\cores\arduino/api/Interrupts.h:8:0,
                 from C:\Users\123sa\.platformio\packages\framework-arduino-samd\cores\arduino/api/ArduinoAPI.h:29,
                 from C:\Users\123sa\.platformio\packages\framework-arduino-samd\cores\arduino/Arduino.h:23,
                 from src\main.cpp:1:
C:\Users\123sa\.platformio\packages\framework-arduino-samd\cores\arduino/api/Common.h: In instantiation of 'decltype (((b < a) ? b :  a)) min(const T&, const L&) [with T = int; L = unsigned int; decltype (((b < a) ? b :  a)) = unsigned int]':
src\passthrough.h:5:60:   required from here
C:\Users\123sa\.platformio\packages\framework-arduino-samd\cores\arduino/api/Common.h:126:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     return (b < a) ? b : a;
            ~~~^~~~
Compiling .pio\build\nano33iot\FrameworkArduino\api\Common.cpp.o
Archiving .pio\build\nano33iot\libFrameworkArduinoVariant.a
Compiling .pio\build\nano33iot\FrameworkArduino\api\IPAddress.cpp.o
Compiling .pio\build\nano33iot\FrameworkArduino\api\PluggableUSB.cpp.o
Compiling .pio\build\nano33iot\FrameworkArduino\api\Print.cpp.o
Compiling .pio\build\nano33iot\FrameworkArduino\api\Stream.cpp.o
Compiling .pio\build\nano33iot\FrameworkArduino\api\String.cpp.o
Compiling .pio\build\nano33iot\FrameworkArduino\compact\dtostrf.c.o
Compiling .pio\build\nano33iot\FrameworkArduino\cortex_handlers.c.o
Compiling .pio\build\nano33iot\FrameworkArduino\delay.c.o
Compiling .pio\build\nano33iot\FrameworkArduino\hooks.c.o
Compiling .pio\build\nano33iot\FrameworkArduino\itoa.c.o
Compiling .pio\build\nano33iot\FrameworkArduino\main.cpp.o
Compiling .pio\build\nano33iot\FrameworkArduino\new.cpp.o
Compiling .pio\build\nano33iot\FrameworkArduino\pulse.c.o
Compiling .pio\build\nano33iot\FrameworkArduino\pulse_asm.S.o
Compiling .pio\build\nano33iot\FrameworkArduino\startup.c.o
Compiling .pio\build\nano33iot\FrameworkArduino\wiring.c.o
Compiling .pio\build\nano33iot\FrameworkArduino\wiring_analog.c.o
Compiling .pio\build\nano33iot\FrameworkArduino\wiring_digital.c.o
Compiling .pio\build\nano33iot\FrameworkArduino\wiring_private.c.o
Compiling .pio\build\nano33iot\FrameworkArduino\wiring_shift.c.o
Archiving .pio\build\nano33iot\libFrameworkArduino.a
Linking .pio\build\nano33iot\firmware.elf
Checking size .pio\build\nano33iot\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]  12.5% (used 4092 bytes from 32768 bytes)
Flash: [          ]   4.6% (used 12028 bytes from 262144 bytes)
Building .pio\build\nano33iot\firmware.bin
Configuring upload protocol...
AVAILABLE: atmel-ice, blackmagic, jlink, sam-ba
CURRENT: upload_protocol = sam-ba
Looking for upload port...
Auto-detected: COM20
Forcing reset using 1200bps open/close on port COM20
Waiting for the new upload port...
Uploading .pio\build\nano33iot\firmware.bin
Atmel SMART device 0x10010005 found
Erase flash
done in 0.817 seconds

Write 12028 bytes to flash (188 pages)

[==========                    ] 34% (64/188 pages)
[====================          ] 68% (128/188 pages)
[==============================] 100% (188/188 pages)
done in 0.094 seconds

Verify 12028 bytes of flash with checksum.
Verify successful
done in 0.011 seconds
CPU reset.
========================= [SUCCESS] Took 8.13 seconds =========================

Environment    Status    Duration
-------------  --------  ------------
nano33iot      SUCCESS   00:00:08.126
========================= 1 succeeded in 00:00:08.126 =========================
pio pkg exec -p tool-esptoolpy -- esptool.py --baud 921600 --before default_reset --after hard_reset write_flash --flash_size detect --erase-all 0x0 .pio/BlynkNCP/v0.6.2/BlynkNCP_nina_w102.flash.bin
Using tool-esptoolpy@1.40501.0 package
C:\Users\123sa\.platformio\python3\python.exe: can't open file 'C:\Users\123sa\Desktop\BlynkNcpExample-main\esptool.py': [Errno 2] No such file or directory
*** Error 2
*** [upload_ncp] Explicit exit, status 1
========================================================== [FAILED] Took 17.07 seconds ==========================================================

Environment    Status    Duration
-------------  --------  ------------
nano33iot      FAILED    00:00:17.068
===================================================== 1 failed, 0 succeeded in 00:00:17.068 =====================================================PS C:\Users\123sa\Desktop\BlynkNcpExample-main>

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

**Comment by vshymanskyy** [comment]
I think your platformio is outdated.
Please update it to the latest version and retry

**Comment by Sachinmc73** [comment]
im using v3.3.1 i think it is latest version

**Comment by vshymanskyy** [comment]
```log
$ platformio upgrade
Please wait while upgrading PlatformIO Core ...
$ platformio --version
PlatformIO Core, version 6.1.10b1
```

**Comment by vshymanskyy** [comment]
Added it to the [Troublehooting section](https://github.com/blynkkk/BlynkNcpExample/blob/main/README.md#troubleshooting)

**Comment by Sachinmc73** [comment]
PS C:\Users\123sa\Desktop\BlynkNcpExample-main> platformio upgrade
You're up-to-date!
PlatformIO 6.1.9 is currently the newest version available.

**Comment by Sachinmc73** [comment]
C:\Users\123sa\.platformio\python3\python.exe: can't open file 'C:\Users\123sa\Desktop\BlynkNcpExample-main\esptool.py': [Errno 2] No such file or directory
*** Error 2

why is this error coming? actually I could not find any file called esptool.py in my directory

**Comment by vshymanskyy** [comment]
There was such a bug in PIO, and it was fixed...
Please try updating to the development version:
```
pio upgrade --dev
pio --version
pio pkg update

pio run -e nano33iot -t upload_ncp
```

**Comment by Sachinmc73** [comment]
wo hooo thank you.
finally connected to blynk.

**Comment by Sachinmc73** [comment]
pio upgrade --dev
pio --version
pio pkg update

pio run -e nano33iot -t upload_ncp

better add this to troubleshoot section

**Comment by vshymanskyy** [comment]
I'm now consulting with platformio on how to handle it properly.
Forcing everyone into the `development` branch is not an option...

**Comment by Sachinmc73** [comment]
ok.
I also need your help with blynk using python on my raspberry pi.

**Comment by vshymanskyy** [comment]
It is best to post it on community.blynk.cc

**Comment by vshymanskyy** [comment]
@Sachinmc73 PlatformIO stable was updated to `v6.1.10` and contains the relevant bugfix
