### ISSUE TITLE
Use NCP without using Edgent

### ISSUE THREAD

**Issue by Sachinmc73** [blynkkk/BlynkNcpExample#8]
hi 
I wanted to use blynk .ncp without using edgent because i am not intrested in wifi provisioning using smartphone
I want the auth token to be hardcoded to my device.
also I want to use multiple Hardware devices(multiple nano 33 iot boards) to connect to a single blynk device this is somehow not possible with the existing example provided.

**Comment by vshymanskyy** [comment]
We can provide a way to use the static token.
Nano 33 IoT is a self-sufficient Blynk device, so connecting multiple such boards to a single device is out of scope of this technology.
Blynk requires each device to have a unique authentication token.

**Comment by Sachinmc73** [comment]
> We can provide a way to use the static token.
please let me know how to do this.

> Nano 33 IoT is a self-sufficient Blynk device, so connecting multiple such boards to a single device is out of scope of this technology.
consider a scenario where I have multiple sensors at different corner of a room connected to dedicated Arduino boards now i want to show this on the same blynk dashboard. in this case it is useful.

**Comment by vshymanskyy** [comment]
> I want the auth token to be hardcoded to my device.

hardcoding the auth tokens has lots of downsides, makes the OTA process painstaking, etc.
Why do you want to stick to static tokens?

FYI, Blynk Cloud **no longer** allows connecting multiple devices with the same auth token.
